---

- name: Ensure podman repository is enabled
  template:
    src: "{{ role_path }}/files/yum.repos.d/{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: "root"
    group: "root"
    mode: 0644
  with_items:
    - podman.repo
  when: matrix_podman_installation_enabled|bool and matrix_podman_package_name == 'podman'

#- name: Ensure podman's RPM key is trusted
#  rpm_key:
#    state: present
#    key: https://download.podman.com/linux/centos/gpg
#  when: matrix_podman_installation_enabled|bool and matrix_podman_package_name == 'podman'

- name: Ensure yum packages are installed
  yum:
    name:
      - "{{ matrix_ntpd_package }}"
      - fuse
    state: latest
    update_cache: yes

- name: Ensure podman is installed
  yum:
    name:
      - "{{ matrix_podman_package_name }}"
      - podman
    state: latest
  when: matrix_podman_installation_enabled|bool
